import { Product } from '../schemas/product.schema';

export const seedProducts: Partial<Product>[] = [
  {
    name: 'Premium Whey Protein',
    description: 'High-quality whey protein powder for muscle recovery and growth.',
    price: 49.99,
    stock: 100,
    category: 'proteins',
    images: ['https://ts3.mm.bing.net/th?id=OIP.hu5_uzw3tuz685qdtkFXnwHaJd&pid=15.1'],
    rating: 4.5,
    numReviews: 125,
    featured: true,
    reviews: [],
    discount: 0,
    brand: 'OptimumNutrition',
    tags: ['protein', 'whey', 'muscle', 'recovery'],
    nutritionInfo: {
      servingSize: '30g',
      servingsPerContainer: 30,
      calories: 120,
      protein: 24,
      carbohydrates: 3,
      fat: 1,
    },
  },
  {
    name: 'Pre-Workout Energy Boost',
    description: 'Advanced pre-workout formula for enhanced performance and focus.',
    price: 39.99,
    stock: 75,
    category: 'pre-workout',
    images: ['https://th.bing.com/th/id/OIP.DH5igwSm_m0xYy7xZESlwAHaJZ?w=145&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7'],
    rating: 4.3,
    numReviews: 89,
    featured: true,
    reviews: [],
    discount: 10,
    brand: 'CellucorC4',
    tags: ['pre-workout', 'energy', 'focus', 'performance'],
    nutritionInfo: {
      servingSize: '6.5g',
      servingsPerContainer: 30,
      calories: 5,
      protein: 0,
      carbohydrates: 1,
      fat: 0,
    },
  },
  {
    name: 'BCAA Recovery Complex',
    description: 'Essential amino acids for muscle recovery and endurance.',
    price: 29.99,
    stock: 150,
    category: 'amino-acids',
    images: ['https://th.bing.com/th/id/OIP._V0KFg2iHJOr06Eiz26BPwHaJ4?w=136&h=181&c=7&r=0&o=5&dpr=1.3&pid=1.7'],
    rating: 4.7,
    numReviews: 67,
    featured: false,
    reviews: [],
    discount: 0,
    brand: 'Scivation',
    tags: ['bcaa', 'amino acids', 'recovery', 'endurance'],
    nutritionInfo: {
      servingSize: '7g',
      servingsPerContainer: 30,
      calories: 5,
      protein: 0,
      carbohydrates: 0,
      fat: 0,
    },
  },
]; 